version: '3.8'

services:
  node-app:
    container_name: node-container
    image: node:alpine
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    command: npm run dev
    ports:
      - "3333:3333"

  nginx:
    container_name: nginx-container
    image: nginx:alpine
    ports:
      - "5555:5555"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node-app
